package com.example.jpa.service;

import com.example.jpa.dto.RoleDTO;
import com.example.jpa.mapper.RoleMapper;
import com.example.jpa.model.IcesiRole;
import com.example.jpa.repository.RoleRepository;
import lombok.AllArgsConstructor;
import lombok.SneakyThrows;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
@AllArgsConstructor
public class RoleService {

    private final RoleRepository roleRepository;
    private final RoleMapper roleMapper;

    @SneakyThrows
    public RoleDTO save(RoleDTO roleDTO){
        //Role name should be unique
        if (roleRepository.findByName(roleDTO.getName()).isPresent()){
            throw new RuntimeException("Role name already exists");
        }
        IcesiRole role = roleMapper.fromRoleDTO(roleDTO);
        role.setRoleId(UUID.randomUUID()); //Role Id is generated by the service
        return roleMapper.fromRole(roleRepository.save(role));
    }
}
