package com.Icesi.TallerJPA.enums;

import lombok.Getter;

@Getter
public enum ErrorConstants {
    CODE_UD_01("EMAIL ALREADY EXIST"),
    CODE_UD_02("PHONE NUMBER ALREADY EXIST"),
    CODE_UD_03("PHONE NUMBER AND EMAIL ALREADY EXIST"),
    CODE_UD_04("USER ROLE CANNOT BE NULL"),
    CODE_UD_05("ROLE NAME ALREADY EXIST"),
    CODE_UD_06("ACCOUNT ALREADY EXISTS"),
    CODE_UD_07("BALANCE CANNOT BE LESS THAN 0"),
    CODE_UD_08("ACCOUNT NOT FOUND"),
    CODE_UD_09("IT IS NOT POSSIBLE TO CHANGE THE STATUS OF THE ACCOUNT"),
    CODE_UD_10("INSUFFICIENT BALANCE"),
    CODE_UD_11("YOU DO NOT HAVE ENOUGH MONEY TO MAKE THIS TRANSFER"),
    CODE_UD_12("INVALID VALUE"),
    CODE_UD_13("THIS TYPE OF ACCOUNT DOES NOT ALLOW TO MAKE TRANSFERS"),
    CODE_UD_14("YOU CANNOT CREATE AN ACCOUNT WITH BALANCE LESS OR EQUAL TO 0"),
    CODE_UD_15("USER DOES NOT EXIST");
    //

    private final String message;

    ErrorConstants(String message) {
        this.message = message;
    }
}
